name: Staging VPS Deployment on pull

on:
  push:
    branches:
      - 'release/**'
      - 'hotfix/**'

  pull_request:
    branches:
      - 'release/**'
      - 'hotfix/**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Copy repository contents via scp
      uses: appleboy/scp-action@master
      env:
        HOST: ${{ secrets.HOST }}
        USERNAME: ${{ secrets.USERNAME }}
        PORT: ${{ secrets.PORT }}
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        source: "."
        target: "/var/www/evanescence-client"

    - name: Executing remote command
      uses: appleboy/ssh-action@master
      env:
        STAGING_API_BASE_URL: ${{ secrets.STAGING_API_BASE_URL }}
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        envs: STAGING_API_BASE_URL
        script: |
          export REACT_API_BASE_URL=$STAGING_API_BASE_URL

          cd /var/www/evanescence-client
          npm install --prefer-offline --no-audit --progress=false
          npm run build:staging
