name: Staging VPS Deployment on pull

on:
  push:
    branches:
      - 'release/**'
      - 'hotfix/**'

  pull_request:
    branches:
      - 'release/**'
      - 'hotfix/**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.head.sha }}

    - name: Extract branch name
      shell: bash
      run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
      id: extract_branch

    - name: Executing remote command
      uses: appleboy/ssh-action@master
      env:
        STAGING_API_BASE_URL: ${{ secrets.STAGING_API_BASE_URL }}
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        envs: STAGING_API_BASE_URL, BRANCH_NAME
        script: |
          export REACT_API_BASE_URL=$STAGING_API_BASE_URL

          cd /var/www/evanescence-client

          git fetch
          git checkout $BRANCH_NAME
          git pull origin

          # npm install --prefer-offline --no-audit --progress=false
          npm run build:staging
