name: Staging VPS Deployment on pull

on:
  push:
    branches:
      - 'release/**'
      - 'hotfix/**'

  pull_request:
    branches:
      - 'release/**'
      - 'hotfix/**'

jobs:
  build-and-deploy:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.head.sha }}
        persist-credentials: false

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Extract branch name
      shell: bash
      run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
      id: extract_branch

    - name: Install and Build 🔧 # This example project is built using npm and outputs the result to the 'build' folder. Replace with the commands required to build your project, or remove this step entirely if your site is pre-built.
      env:
        STAGING_API_BASE_URL: ${{ secrets.STAGING_API_BASE_URL }}
      run: |
        export REACT_API_BASE_URL=$STAGING_API_BASE_URL
        export REACT_API_BASE_URL=staging
        export BUILD_PATH='./staging'
        env
        npm install
        npm run build:staging

    - name: Executing remote command
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        script: |
          cd /var/www/evanescence-client

          git fetch
          git checkout $BRANCH_NAME
          git pull origin